Playerbot functionnality to use (channels / emote / say / yell / guild) chat
liyunfan1223/mod-playerbots pull request #386
Opened 2024-07-26 09:43 UTC by atidot3

tested out with 5000 active bots havent seen any lag but it spam alot.

2024-07-26 12:42 UTC, atidot3 commented
PR need core changes:
https://github.com/liyunfan1223/azerothcore-wotlk/pull/15

2024-07-27 01:20 UTC, liyunfan1223 requested changes
Good work, please make some changes as required.

It looks like we need to test with different dbc files on different servers. And it's still in the debug phase, it's best to set a config to control the feature on/off (default is off).

2024-07-27 01:20 UTC, liyunfan1223 commented on src/AiFactory.cpp
> +        engine->removeStrategy("cast time");
Don’t just change it for granted, you need to make sure the strategies are working correctly and explain what specific problem they solve.

2024-07-27 01:20 UTC, liyunfan1223 commented on src/AiFactory.cpp
> +    Engine* nonCombatEngine = new Engine(facade, aiObjectContext);
Don't adjust the code style in this PR, we need to focus on the feature you introduced.

2024-07-27 01:20 UTC, liyunfan1223 commented on src/PlayerbotMgr.cpp
> +    WorldSession* botSession = new WorldSession(botAccountId, "", nullptr, SEC_PLAYER, EXPANSION_WRATH_OF_THE_LICH_KING, time_t(0), sWorld->GetDefaultDbcLocale(), 0, false, false, 0, true);
After the change, you should modify the calculation of spell id value

https://github.com/liyunfan1223/mod-playerbots/blob/8816758490a0e33327f53af2c31d1f369044be5a/src/strategy/values/SpellIdValue.cpp#L193

to `LocaleConstant loc = LOCALE_enUS;`

2024-07-27 01:20 UTC, liyunfan1223 commented on src/AiFactory.cpp
> +        nonCombatEngine->removeStrategy("follow");
Don’t just change it for granted, you need to make sure the strategies are working correctly and explain what specific problem they solve.

2024-07-27 01:22 UTC, liyunfan1223 commented on src/AiFactory.cpp
> +            engine->addStrategies("behind", "stealth", nullptr);
Don’t just change it for granted, you need to make sure the strategies are working correctly and explain what specific problem they solve.

2024-07-27 07:41 UTC, atidot3 commented on src/AiFactory.cpp
> +        engine->removeStrategy("cast time");
yea forgot to switch bvranch ... sry

2024-07-28 02:41 UTC, liyunfan1223 requested changes
I did a test myself, based on a commit to https://github.com/atidot3/mod-playerbots/commit/5f60ded4198a7eba57ceb59f74e0619109166820. Overall it works fine, but there are a few issues present

1. With EnableGreet or RandomBotEmote enabled, grouping a number of bots (like a 25-man team) and summoning them together produces excessive greeting and emote content.

2. They actively talk in the world channel, but I don't get messages in other channels (like trade or lfg).

We can merge it first after remove this error log. Other issues can be resolved after merging. It would be great if more people were involved in testing and developing this feature and giving feedback.

2024-07-28 02:41 UTC, liyunfan1223 commented on src/strategy/Engine.cpp
> +                LOG_ERROR("playerbots", "Action: {} - is UNKNOWN - c:{} l:{}", actionNode->getName().c_str(), botAI->GetBot()->getClass(), botAI->GetBot()->GetLevel());
remove this error log

2024-07-28 10:36 UTC, liyunfan1223 approved these changes

2024-07-28 10:36 UTC, merged